language: node_js
node_js:
  - '10'
cache:
  directories:
    - node_modules
deploy:

before_script:
  - 'npm i -g parcel-bundler'
  - 'npm ci'
script:
  - 'npm run build'
after_success:
  - surge --project ./dist --domain recepten.surge.sh
